default['railslove']['packages'] =  [] # specifiy addons eg mysql, postgresql or ldap
default['railslove']['companies'] = ["railslove"] # specifiy which companies should have access
default['railslove']['domain'] = "railslabs.com"
default['railslove']['manage_dns_records'] = true
default['railslove']['route53']['databag'] = "aws"
default['railslove']['route53']['item'] = "route53"
default['railslove']['backup']['databag'] = "aws"
default['railslove']['backup']['item'] = "s3"
default['railslove']['rake']['version'] = nil
default['railslove']['ohai_plugins'] = []
default['railslove']['docker']['containers'] = []
default['railslove']['docker']['registry_url'] = 'https://index.docker.io/v1/'
